[package]
name = "pwdb"
version = "0.1.0"
authors = ["Will Dicharry <wdicharry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.26"
base64 = "0.11.0"
hex = "0.4.0"
serde = "1.0.44"
